name: Check

permissions:
  checks: write
  actions: read
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [ "*" ]

jobs:

  flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@6ed004b9ccb68dbc28e7c85bee15fa93dbd214ac
      with:
        nix_path: nixpkgs=channel:nixos-23.11
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: DeterminateSystems/magic-nix-cache-action@eeabdb06718ac63a7021c6132129679a8e22d0c7

    - run: nix flake check
